add option to not resolve symlinks
Amaimersion/remove-files-webpack-plugin pull request #40
Opened 2021-12-07 20:26 UTC by AprilArcus

Fixes https://github.com/Amaimersion/remove-files-webpack-plugin/issues/39

Adds an option to ignore symlinks when recursively deleting directory contents

2021-12-08 13:52 UTC, Amaimersion commented
Based on #39 I can say that symlinks are not being resolved. I suppose you just want to remove symlink itself?

2021-12-09 22:49 UTC, AprilArcus commented
yes exactly, the way `rm -rf` would

2021-12-13 07:36 UTC, Amaimersion requested changes
Let's delete symlinks silently because it is default behavior of `rm -rf`. I think there is no point to complicate it with another parameter because it is already considered as default and expected behavior.

2021-12-13 07:36 UTC, Amaimersion commented on src/plugin.js
> +            symlinks: true,
Let's remove it. We will delete symlinks silently because it is default behavior of `rm -rf`.

2021-12-13 07:36 UTC, Amaimersion commented on README.md
> +|        symlinks          |                                          `boolean`                                           |   `true`    |    All    |
Let's remove it. We will delete symlinks silently because it is default behavior of rm -rf.

2021-12-13 07:36 UTC, Amaimersion commented on src/fs.js
> +            } else if (stat.isFile() || (stat.isSymbolicLink() && !params.symlinks)) {
Let's remove it. We will delete symlinks silently because it is default behavior of rm -rf. Just keep `(stat.isFile() || stat.isSymbolicLink())`

2021-12-13 07:40 UTC, AprilArcus commented
I think it would be most appropriate to make two releases, 1.5.0 with a flag to change the behavior, and 2.0.0 with the flag removed and the new default.

2021-12-13 07:42 UTC, Amaimersion commented
I will add it in 1.5.0 release because it is breaking changes. There is no point in 2.0.0 version for that feature only because it is not major release.

2021-12-13 07:45 UTC, AprilArcus commented
Most nom packages uses semantic versioning, in which new features are introduced in minor versions, and breaking changes in major versions. But you're the maintainer; it's up to you. Would you like me to push the changes to requested, or will you take it from here?

2021-12-13 07:56 UTC, Amaimersion commented
Well, I wouldn't call it "new feature". Rather I will say that it is "bug fix" because removing of symlinks is expected behavior by default when you say "remove this folder and its content".

I would like to take changes from this PR in order to keep track on this PR for possible future discussions. I can push more commits to this PR with my changes that I think are more appropriate for this "bug fix", not "new feature". Tell me that you think

2021-12-13 07:59 UTC, AprilArcus commented
I suppose I can't think of a situation in which following symlinks would actually be desirable. Let's leave out the option and call it a bug fix, as you say.

2021-12-13 08:01 UTC, Amaimersion commented
Please read the #39 Symlinks are not being followed. Only symlinks itself are being removed, not its content.

2021-12-13 08:03 UTC, AprilArcus commented
I think we agree that `(stat.isFile() || stat.isSymbolicLink())` is the correct behavior.

2021-12-13 08:10 UTC, Amaimersion approved these changes

2021-12-13 08:16 UTC, merged